apiVersion: v1
kind: Service
metadata:
  name: cliet-svc
  labels:
    app: client
spec:
  type: NodePort
  ports:
  - protocol: TCP
    port: 9091
    nodePort: 30001
  selector:
    app: client
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-app
spec:
  selector:
    matchLabels:
      app: client
  replicas: 1
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
      - name: client
        image: rogerdockerk8/client:v5
        env:
          - name: SERVICE_NAME
            value: crud-svc
        ports:
        - containerPort: 9091
